server:
  port: 9092

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DBNAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}