server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/TrivagoAuthDB
  jpa:
    hibernate:
      ddl-auto: update


my-application:
  user-profile-end-point: "http://localhost:9092/user-profile"

buraya-canimin-istedigini-yazarim:
  okuyabilirim: "bu nedir ya hu ?"